version: '3'

services: 
  db:
    build: ./docker/db
    image: mysql:5.7
    container_name: abfm_db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: abfm_test
      MYSQL_USER: abfm
      MYSQL_PASSWORD: abfm
      TZ: 'Asia/Tokyo'
    volumes: 
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    - ./log/mysql:/var/log/mysql
    ports: 
    - 3306:3306
