spring:
  datasource:
    url: jdbc:mysql://localhost:3306/abfm_test
    username: abfm
    password: abfm
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

